### ISSUE TITLE
Cannot run program "python2" (in directory "."): error=2, No such file or directory

### ISSUE THREAD

**Issue by geralt-write-code** [ldbc/ldbc_snb_datagen_hadoop#19]
Running Parameter Generation
Generating Interactive Parameters
Error during execution
Cannot run program "python2" (in directory "."): error=2, No such file or directory
Exception in thread "main" java.io.IOException: Cannot run program "python2" (in directory "."): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at ldbc.snb.datagen.LdbcDatagen.runGenerateJob(LdbcDatagen.java:305)
	at ldbc.snb.datagen.LdbcDatagen.main(LdbcDatagen.java:344)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more

this exception occurs when Serializing static graph.
I don't know what directory it refers.
running on my macbookpro2019 64g ram

**Comment by szarnyasg** [comment]
You can install [`python2`](https://docs.python-guide.org/starting/install/osx/) to make this work.

But if you just need the default substitution parameters for SNB Interactive, I wouldn't bother with installing a deprecated Python version -- just grab the pre-generated parameters: https://github.com/ldbc/data-sets-surf-repository#substitution-parameters

**Comment by geralt-write-code** [comment]
> You can install [`python2`](https://docs.python-guide.org/starting/install/osx/) to make this work.
> 
> But if you just need the default substitution parameters for SNB Interactive, I wouldn't bother with installing a deprecated Python version -- just grab the pre-generated parameters: https://github.com/ldbc/data-sets-surf-repository#substitution-parameters

thanks， I'll try it!
