### ISSUE TITLE
exception: Input path does not exist

### ISSUE THREAD

**Issue by simon824** [ldbc/ldbc_snb_datagen_hadoop#23]
running on a distributed Hadoop cluster

# error log
```
************************************************
* Sorting update streams  *
************************************************
23/03/23 10:31:15 INFO client.AHSProxy: Connecting to Application History server at hadoop011/10.21.33.11:13200
23/03/23 10:31:15 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
23/03/23 10:31:16 INFO mapreduce.JobResourceUploader: Disabling Erasure Coding for path: /user/hdfs/.staging/job_1679366819090_0118
23/03/23 10:31:16 INFO mapreduce.JobSubmitter: Cleaning up the staging area /user/hdfs/.staging/job_1679366819090_0118
Error during execution
Input path does not exist: hdfs://hadoop3-cluster/user/hdfs/hadoop/temp_updateStream_person_0_0
Exception in thread "main" org.apache.hadoop.mapreduce.lib.input.InvalidInputException: Input path does not exist: hdfs://hadoop3-cluster/user/hdfs/hadoop/temp_updateStream_person_0_0
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:332)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.listStatus(FileInputFormat.java:274)
        at org.apache.hadoop.mapreduce.lib.input.SequenceFileInputFormat.listStatus(SequenceFileInputFormat.java:59)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:396)
        at org.apache.hadoop.mapreduce.JobSubmitter.writeNewSplits(JobSubmitter.java:310)
        at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:327)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:200)
        at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1570)
        at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1567)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1567)
        at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1588)
        at ldbc.snb.datagen.hadoop.serializer.HadoopUpdateStreamSorterAndSerializer.run(HadoopUpdateStreamSorterAndSerializer.java:130)
        at ldbc.snb.datagen.LdbcDatagen.runGenerateJob(LdbcDatagen.java:204)
        at ldbc.snb.datagen.LdbcDatagen.main(LdbcDatagen.java:344)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:318)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:232)
```

# params.ini
```
ldbc.snb.datagen.generator.scaleFactor:snb.interactive.100

ldbc.snb.datagen.serializer.dynamicActivitySerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.activity.CsvBasicDynamicActivitySerializer
ldbc.snb.datagen.serializer.dynamicPersonSerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.person.CsvBasicDynamicPersonSerializer
ldbc.snb.datagen.serializer.staticSerializer:ldbc.snb.datagen.serializer.snb.csv.staticserializer.CsvBasicStaticSerializer

```

**Comment by szarnyasg** [comment]
Hi @simon824, unfortunately, we at the SNB task force do not have the resources to maintain this library as we moved to a Spark setup.

We have pre-generated the data sets that are available for download, see:
https://github.com/ldbc/data-sets-surf-repository#social-network-benchmark-snb-interactive-v1
